### ISSUE TITLE
Learning Cross-Modal Deep Representations for Robust Pedestrian Detection

### ISSUE THREAD

**Issue by guanfuchen** [guanfuchen/cvpr_review#561]
|id|title|author|year|
|---|---|---|---|
|561|Learning Cross-Modal Deep Representations for Robust Pedestrian Detection|Xu, Dan and Ouyang, Wanli and Ricci, Elisa and Wang, Xiaogang and Sebe, Nicu|2017|

**Comment by bigbing77777** [comment]
有pytorch版的代码复现吗

**Comment by guanfuchen** [comment]
没有关注这个哎
